const ErrorCode = {
  API_KEY_EXPIRED: 'api_key_expired',
  API_KEY_INSUFFICIENT_PERMISSIONS: 'api_key_insufficient_permissions',
  API_KEY_MISSING: 'api_key_missing',
  API_KEY_INVALID: 'api_key_invalid',
  API_KEY_REVOKED: 'api_key_revoked',
  CREDENTIAL_ALREADY_USED: 'credential_already_used',
  CREDENTIAL_EXPIRED: 'credential_expired',
  CREDENTIAL_INVALID: 'credential_invalid',
  CREDENTIAL_STATUS_NOT_VALID: 'credential_status_not_valid',
  CREDENTIAL_STATUS_IMMUTABLE: 'credential_status_immutable',
  CREDENTIAL_STATUS_INVALID: 'credential_token_invalid',
  CREDENTIAL_TOKEN_EXPIRED: 'credential_token_expired',
  HEADER_EMPTY: 'header_empty',
  HEADER_MISSING: 'header_missing',
  NOT_FOUND: 'not_found',
  VERIFICATION_CODE_INVALID: 'verification_code_invalid',
  VERIFICATION_CODE_USED: 'verification_code_used',
  PARSING_FAILED: 'parsing_failed',
  PARAMETER_EMPTY: 'parameter_empty',
  PARAMETER_INVALID: 'parameter_invalid',
  PARAMETER_MISSING: 'parameter_missing',
  PARAMETER_UNKNOWN: 'parameter_unknown',
  PARAMETERS_EXCLUSIVE: 'parameters_exclusive',
  PASSWORD_INVALID: 'password_invalid',
  PUBLIC_KEY_NOT_FOUND: 'public_key_not_found',
  SESSION_EXPIRED: 'session_expired',
  SESSION_INACTIVE: 'session_inactive',
  SESSION_REVOKED: 'session_revoked',
  SESSION_TOKEN_INVALID: 'session_token_invalid',
  SESSION_TOKEN_EXPIRED: 'session_token_expired',
  USER_BLOCKED: 'user_blocked'
}

export default ErrorCode
